### PR TITLE
feat: add endpoint for getting table; fix: correctly perform and handle database call (async)

### LINKED ISSUE #29: Expose endpoint to view table entries

### PR DESCRIPTION
**Pull request by alanhwu**
Closes #29

### CODE REVIEW

File: backend/db/db.ts [hunk 1]
```diff
@@ -74,17 +74,17 @@ export function addSubmission(submission: Submission) {
...
+        reject(err);
+      } else {
+        console.log("Received: ", rows);
+        resolve(rows);
+      }
     });
   });
-  return submissionRows;
-}
+}
```
Comment (nareha) [inline backend/db/db.ts:90]: Nit: Could you add an empty line at EOF?

**Review by steveez123 — APPROVED** [review]

**Review by jc-tung — APPROVED** [review]

File: backend/db/db.ts (hunk 1 above)
Comment (alanhwu) [reply backend/db/db.ts]: done
